#!/usr/bin/env bash
# https://docs.romm.app/latest/Tools/Igir-Collection-Manager/#initial-setup-steps
# https://igir.io/usage/desktop/romm/

set -ou pipefail

BASE_DIR=/mnt/user/games

cd $BASE_DIR

/mnt/user/appdata/igir-portable/igir \
  link \
  --link-mode symlink \
  -d $BASE_DIR/romimport/dats/No-Intro*.zip \
  --dat-name-regex-exclude "/encrypted|source code|headerless|ByteSwapped|8-bit Family|MSX/i" \
  -i $BASE_DIR/roms/No-Intro/ \
  --input-checksum-max CRC32 \
  --input-checksum-archives never \
  -o $BASE_DIR/roms/mister/{mister}/ \
  --dir-letter \
  --dat-threads 1 \
  --no-bios \
  --overwrite-invalid \
  --only-retail \
  --single \
  --prefer-language EN \
  --prefer-region USA,WORLD,EUR,JPN \
  --prefer-retail \
  --prefer-parent

/mnt/user/appdata/igir-portable/igir \
  link \
  --link-mode symlink \
  -d $BASE_DIR/romimport/dats/Redump/* \
  --dat-name-regex-exclude "/encrypted|source code|headerless|MSX/i" \
  -i $BASE_DIR/roms/Redump/ \
  --input-checksum-max CRC32 \
  --input-checksum-archives never \
  -o $BASE_DIR/roms/mister/{mister}/ \
  --dir-letter \
  --dat-threads 1 \
  --no-bios \
  --overwrite-invalid \
  --only-retail \
  --single \
  --prefer-language EN \
  --prefer-region USA,WORLD,EUR,JPN \
  --prefer-retail \
  --prefer-parent