#!/usr/bin/env bash

no_intro_dirs=(
"Atari - Atari 2600/"
"Atari - Atari 2600 (Aftermarket)/"
"Atari - Atari 2600 (Private)/"
"Atari - Atari 5200/"
"Atari - Atari 7800 (A78) (Aftermarket)/"
"Atari - Atari 7800 (A78) (Private)/"
"Atari - Atari 7800 (BIN)/"
"Atari - Atari 7800 (BIN) (Aftermarket)/"
"Atari - Atari 7800 (BIN) (Private)/"
"Atari - Atari Jaguar (ABS) (Aftermarket)/"
"Atari - Atari Jaguar (COF) (Aftermarket)/"
"Atari - Atari Jaguar (J64)/"
"Atari - Atari Jaguar (J64) (Aftermarket)/"
"Atari - Atari Jaguar (JAG)/"
"Atari - Atari Jaguar (JAG) (Aftermarket)/"
"Atari - Atari Jaguar (ROM)/"
"Atari - Atari Jaguar (ROM) (Aftermarket)/"
"Atari - Atari Lynx (BLL)/"
"Atari - Atari Lynx (BLL) (Aftermarket)/"
"Atari - Atari Lynx (LNX)/"
"Atari - Atari Lynx (LNX) (Aftermarket)/"
"Atari - Atari Lynx (LNX) (Private)/"
"Atari - Atari Lynx (LYX)/"
"Atari - Atari Lynx (LYX) (Aftermarket)/"
"Atari - Atari Lynx (LYX) (Private)/"
"NEC - PC Engine - TurboGrafx-16/"
"NEC - PC Engine - TurboGrafx-16 (Aftermarket)/"
"NEC - PC Engine - TurboGrafx-16 (Private)/"
"NEC - PC Engine SuperGrafx/"
"NEC - PC Engine SuperGrafx (Aftermarket)/"
"Nintendo - Game Boy/"
"Nintendo - Game Boy (Aftermarket)/"
"Nintendo - Game Boy (Private)/"
"Nintendo - Game Boy Advance/"
"Nintendo - Game Boy Advance (Aftermarket)/"
"Nintendo - Game Boy Advance (Multiboot)/"
"Nintendo - Game Boy Advance (Play-Yan)/"
"Nintendo - Game Boy Advance (Private)/"
"Nintendo - Game Boy Advance (Video)/"
"Nintendo - Game Boy Advance (Video) (Aftermarket)/"
"Nintendo - Game Boy Advance (Video) (Private)/"
"Nintendo - Game Boy Advance (e-Reader)/"
"Nintendo - Game Boy Advance (e-Reader) (Aftermarket)/"
"Nintendo - Game Boy Color/"
"Nintendo - Game Boy Color (Aftermarket)/"
"Nintendo - Game Boy Color (Private)/"
"Nintendo - Nintendo 64 (BigEndian)/"
"Nintendo - Nintendo 64 (BigEndian) (Aftermarket)/"
"Nintendo - Nintendo 64 (BigEndian) (Private)/"
"Nintendo - Nintendo 64DD/"
"Nintendo - Nintendo Entertainment System (Headered)/"
"Nintendo - Nintendo Entertainment System (Headered) (Aftermarket)/"
"Nintendo - Nintendo Entertainment System (Headered) (Private)/"
"Nintendo - Super Nintendo Entertainment System/"
"Nintendo - Super Nintendo Entertainment System (Aftermarket)/"
"Nintendo - Super Nintendo Entertainment System (Private)/"
"Nintendo - Virtual Boy/"
"Nintendo - Virtual Boy (Aftermarket)/"
"Nintendo - Virtual Boy (Private)/"
"SNK - NeoGeo Pocket/"
"SNK - NeoGeo Pocket Color/"
"Sega - 32X/"
"Sega - 32X (Aftermarket)/"
"Sega - Game Gear/"
"Sega - Game Gear (Aftermarket)/"
"Sega - Master System - Mark III/"
"Sega - Master System - Mark III (Aftermarket)/"
"Sega - Master System - Mark III (Private)/"
"Sega - Mega Drive - Genesis/"
"Sega - Mega Drive - Genesis (Aftermarket)/"
"Sega - Mega Drive - Genesis (Private)/"
)

redump_dirs=(
)


for dir in "${no_intro_dirs[@]}"
do
/mnt/user/appdata/rclone-portable/rclone \
	sync \
	myrient:"/files/No-Intro/$dir" \
	"/mnt/user/games/romimport/No-Intro/$dir" \
	-v --multi-thread-streams 0
done

for dir in "${redium_dirs[@]}"
do
/mnt/user/appdata/rclone-portable/rclone \
	sync \
	myrient:"files/Redump/$dir" \
	"/mnt/user/games/romimport/Redump/$dir" \
	-v --multi-thread-streams 0
done
