#!/usr/bin/env bash

no_intro_dirs=(
"Nintendo - Game Boy Advance/"
"Nintendo - Game Boy Advance (Aftermarket)/"
"Nintendo - Game Boy Advance (Private)/"
"Nintendo - Super Nintendo Entertainment System/"
"Nintendo - Super Nintendo Entertainment System (Aftermarket)/"
"Nintendo - Super Nintendo Entertainment System (Private)/"
)

redump_dirs=(
)

for dir in "${no_intro_dirs[@]}"
do
/mnt/user/appdata/rclone-portable/rclone \
	sync \
	myrient:"/files/No-Intro/$dir" \
	"/mnt/user/games/romimport/No-Intro/$dir" \
	-v --multi-thread-streams 0
done

for dir in "${redium_dirs[@]}"
do
/mnt/user/appdata/rclone-portable/rclone \
	sync \
	myrient:"files/Redump/$dir" \
	"/mnt/user/games/romimport/Redump/$dir" \
	-v --multi-thread-streams 0
done
