#!/usr/bin/env bash
# https://docs.romm.app/latest/Tools/Igir-Collection-Manager/#initial-setup-steps
# https://igir.io/usage/desktop/romm/

set -ou pipefail

BASE_DIR=/mnt/user/games

cd $BASE_DIR

# No-Intro 
# https://datomatic.no-intro.org/index.php?page=download&op=daily&s=64
# - Select P/C then Request

/mnt/user/appdata/igir-portable/igir \
  move \
  extract \
  test \
  clean \
  report \
  -d $BASE_DIR/romimport/dats/No-Intro*.zip \
  --dat-name-regex-exclude "/encrypted|source code|headerless|ByteSwapped|8-bit Family|MSX/i" \
  -i $BASE_DIR/romimport/No-Intro/ \
  -i $BASE_DIR/roms/No-Intro/ \
  --input-checksum-max CRC32 \
  --input-checksum-archives never \
  -o $BASE_DIR/roms/No-Intro/ \
  --dir-dat-name \
  --dat-threads 1 \
  --no-bios \
  --overwrite-invalid \
  --only-retail \
  --single \
  --prefer-language EN \
  --prefer-region USA,WORLD,EUR,JPN \
  --prefer-retail \
  --prefer-parent

# redump
# http://redump.org/downloads/

/mnt/user/appdata/igir-portable/igir \
  move \
  test \
  clean \
  report \
  -d $BASE_DIR/romimport/dats/Redump/* \
  --dat-name-regex-exclude "/encrypted|source code|headerless|ByteSwapped|8-bit Family|MSX/i" \
  -i $BASE_DIR/romimport/Redump/ \
  -i $BASE_DIR/roms/Redump/ \
  --input-checksum-max CRC32 \
  --input-checksum-archives never \
  -o $BASE_DIR/roms/Redump/ \
  --dir-dat-name \
  --dat-threads 1 \
  --no-bios \
  --overwrite-invalid \
  --only-retail \
  --single \
  --prefer-language EN \
  --prefer-region USA,WORLD,EUR,JPN \
  --prefer-retail \
  --prefer-parent
 
