#!/usr/bin/env bash
# https://docs.romm.app/latest/Tools/Igir-Collection-Manager/#initial-setup-steps
# https://igir.io/usage/desktop/romm/

set -ou pipefail
cd "/mnt/user/games"

INPUT_DIR=/mnt/user/games/romimport
OUTPUT_DIR=/mnt/user/games/roms

# dats
# https://datomatic.no-intro.org/index.php?page=download&op=daily&s=64
# - Select P/C then Request
#
# http://redump.org/downloads/

/mnt/user/appdata/igir-portable/igir \
  copy \
  exract \
  test \
  clean \
  report \
  -d dats/ \
  -i "${INPUT_DIR}/" \
  -i "${OUTPUT_DIR}/" \
  -o "${OUTPUT_DIR}/{romm}/" \
  --no-bios \
  --overwrite-invalid \
  --only-retail \
  --single \
  --prefer-language EN \
  --prefer-region USA,WORLD,EUR,JPN \
  --prefer-retail \
  --prefer-revision newer
